### ISSUE TITLE
Is it possible to update the code to treat the tau parameter as one that can be solved for within the model?

### ISSUE THREAD

**Issue by GEOSCIENCELXG** [tobiscode/disstans#10]
In the current version, we need to provide a tau value for the logarithmic model; however, tau is a crucial parameter that we would like to estimate instead. 

Is it possible to update the code to treat the tau parameter as one that can be solved for within the model?

Cheers

**Comment by tobiscode** [comment]
Hi,
estimating tau would make the problem heavily non-linear, and is therefore definitely out of the scope and technical possibilities of DISSTANS. An alternative that may or may not work for you in your circumstance (it does for mine), is to use the option to have multiple taus, and estimate coefficients for each of these. The trick here is that a given tau can be well approximated by a weighted sum of multiple other taus. (Also: rarely does nature settle on a single tau anyway.) Check out the documentation for both `Logarithmic` and `Exponential`, they both have this option. Note: you will probably have to regularize.
Cheers

**Comment by GEOSCIENCELXG** [comment]
Hi,

Thanks for your reply. I will try it by inputting multiple taus, but I cannot understand, what you mentioned" Note: you will probably have to regularize."?  how to implement it?

Best

**Comment by tobiscode** [comment]
Hi,
explaining the concept of [regularization](https://en.wikipedia.org/wiki/Regularization_(mathematics)) goes a bit beyond the scope of this Github issue. Apart from estimation text books, you can look at the following DISSTANS parts and then look up their references:

- The solvers [`ridge_regression`](https://tobiscode.github.io/disstans/disstans/solvers.html#ridge-regression) and [`lasso_regression`](https://tobiscode.github.io/disstans/disstans/solvers.html#lasso-regression)
- [Tutorial 2](https://tobiscode.github.io/disstans/tutorials/tutorial_2.html)
- Sections 3.3 and Appendix A.3 in the paper/preprint

Hope that helps!
Cheers
