### ISSUE TITLE
scipy toarray()

### ISSUE THREAD

**Issue by koulali** [tobiscode/disstans#5]
I have noticed that the scipy.sparse.csr_matrix .A method is deprecated and I had to replace it with .toarray() instead to be able to run the examples. I'm using scipy 1.14

**Comment by tobiscode** [comment]
Thanks for pointing this out! Not sure how I missed it since it officially got deprecated in 1.11 and I've been testing with 1.13 for a while 🤔 I fixed it with ddda651d932f4a7acfdcfbf74de0fd22fc564c5c and also pushed the update to PyPI.

Cheers
