### ISSUE TITLE
CME plot shows abnomal large value with graphical_cme() in example_1_longvalleycaldera.py ?

### ISSUE THREAD

**Issue by GEOSCIENCELXG** [tobiscode/disstans#7]
Hi, Tobis

I try     net.graphical_cme(ts_in="raw_filt_res", ts_out=None, annotate_stations=True, save=True, 
                      save_kw_args={'format': 'png'}, 
                      gui_kw_args={}, method="ica",rng=np.random.default_rng(0))

to get the CME timeseries, but there is abnormally large value, do you have any idea about this?

![cme_spatial](https://github.com/user-attachments/assets/31eafc8b-646a-4790-b361-39d9db238332)
![cme_temporal](https://github.com/user-attachments/assets/7e6693c9-a927-448e-b542-2e21fe51e6aa)

**Comment by tobiscode** [comment]
Hi,
looking at the timeseries for the station, this is purely a data issue. CME requires that the input doesn't have large steps anymore, and that all major outliers are removed. P727 does at least still have the latter: http://geodesy.unr.edu/NGLStationPages/stations/P727.sta, compare the raw versus cleaned plots. This is why in Example 1, there's a cleaning step beforehand: https://tobiscode.github.io/disstans/examples/example_1.html#cleaning-the-timeseries - if this step still leaves such large outliers, you would need to adjust your settings.
Cheers
