### ISSUE TITLE
is there a function to plot segments of the raw time series?

### ISSUE THREAD

**Issue by GEOSCIENCELXG** [tobiscode/disstans#9]
Hi Tobias, 

is there a function in the DISSTANS I can use to plot the specific segment of raw time series?

Bests

**Comment by tobiscode** [comment]
Hi,
do you mean a certain time period? All plotting is done using [`Network.gui()`](https://tobiscode.github.io/disstans/disstans/network.html#disstans.network.Network.gui), and you can interactively zoom into and out of time periods. I've meant to integrate a parameter where on can pre-select a timeframe when calling the function in the first place but I haven't gotten around to it yet.
I hope that answers your question.
Cheers

**Comment by GEOSCIENCELXG** [comment]
I got it. that is why I can not get a certain period plot with code: 

net.gui(save=True, station=statname, analyze_kw_args={"t_start": "2011-06-01", "t_end": "2012-08-01"},
        save_kw_args={"format": fmt, "dpi": 300})

**Comment by tobiscode** [comment]
Ah, that's a good point. Yeah, those keyword arguments should still be passed on to the analysis function, but the plotting won't be affected. I'll put this on my to-do list, hopefully I'll get to this in the coming weeks. I hope in the meantime, the interactive zoom is sufficient (you can still save the figures from the interactive figure if you need to).

Cheers

**Comment by tobiscode** [comment]
Added in 59bce4806330c7c34905b41aca9807fcfaabd8ab, feel free to try it out (follow the [full repo clone instructions](https://tobiscode.github.io/disstans/installation.html#full-development-installation), and switch to the `development` branch before the `pip install` step). It'll be a little while until I merge this and the rest of the `development` branch into the main one and publish a proper release.

Cheers

**Comment by tobiscode** [comment]
Now in the main branch and released in version 2.2.

**Comment by GEOSCIENCELXG** [comment]
Thanks, Tobias, It's a very nice tool for GNSS time-series analysis. 

Cheers

**Comment by GEOSCIENCELXG** [comment]
Hi Tobis, I found it is very time consuming when using net.gui to save figures, because it creape the map in loop. could you add a parameter, e.g., mat_load = False, to control MAP creating?  @tobiscode 

    for stat_name in resids_df.index[:4].tolist():
        net.gui(station=stat_name, timeseries="raw", **map_loaded = False**, save=True,
                save_kw_args={"format": fmt, "dpi": 300})

**Comment by tobiscode** [comment]
If you only need timeseries without the map, then the GUI is not the intended way to plot them. I've found whenever one wants to only plot timeseries, it's easier and more customizable if you just make the plot yourself. All the DISSTANS objects are created with that in mind, see for example the way I create timeseries plots in [Tutorial 2](https://tobiscode.github.io/disstans/tutorials/tutorial_2.html#building-a-network). There, I access the `Station` and `Timeseries` objects to plot everything, which you can access dictionary-like, e.g. `net["mystation"]["mytimeseries"]`.
